# Generated by Django 5.2 on 2025-05-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_crud',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='preço_total_quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
