# Generated by Django 5.2 on 2025-05-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_bd_crud_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatorio_de_vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TimeField(auto_now=True)),
                ('produto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('quantidade', models.IntegerField()),
                ('total_quantidade', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
