# Generated by Django 5.2 on 2025-05-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_relatorio_de_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio_de_vendas',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
